In [1]:
import numpy as np

array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [3]:
print("first index"[0])
print("last index"[-1])


f
x


In [11]:
import numpy as np

array=np.array([1,2,3,4,5])
print(array)
print("first index",array[0])
print("last index",array[-1])
doubled_array= array*2
print("The doubled array is",doubled_array)

[1 2 3 4 5]
first index 1
last index 5
The doubled array is [ 2  4  6  8 10]


In [35]:
import numpy as np
a = np.zeros(10)
print(a)
b= np.ones(10)
print(b)
c= np.zeros(10)
print(a+5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [61]:
    import numpy as np
    np.random.seed(122)
    mat= np.random.randint(2,10,size=(3,3))
    print(mat)

[[9 4 4]
 [8 6 8]
 [2 6 9]]
